name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dotnet/ghactions-dotnet-demo

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build --output ./published
    - name: Package
      run: (cd ./published && zip -r ../webapp.zip .)
    - uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: dotnet/ghactions-dotnet-demo/webapp.zip
        
  deploy:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: webapp
          path: webapp
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ghactions-webapp-demo
          package: webapp/webapp.zip

#       - shell: pwsh
#         run: |
#             ./drop/deploy-webapp.ps1 -resourceGroupName aegis-apis `
#                               -packageSource './drop/api.zip' `
#                               -webAppName aegis-apis-teams `
#                               -serviceName teams `
#                               -environmentCode dev
